// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKz9szHnJL4sbRZFAb-BU_CY_UHBt38AQ',
    appId: '1:1014523318355:web:dac21eafaf78f12104f6a6',
    messagingSenderId: '1014523318355',
    projectId: 'automated-attendence-6fc07',
    authDomain: 'automated-attendence-6fc07.firebaseapp.com',
    storageBucket: 'automated-attendence-6fc07.firebasestorage.app',
    measurementId: 'G-QB290CQ88D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVykvO0xiSMgrfqZtS05DNODNV4yasVy4',
    appId: '1:1014523318355:android:24fddb2e66446dba04f6a6',
    messagingSenderId: '1014523318355',
    projectId: 'automated-attendence-6fc07',
    storageBucket: 'automated-attendence-6fc07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ZM-7A6bdNFul5jcNfjPDNm6Gi1GP8qw',
    appId: '1:1014523318355:ios:22b5e935d7b4999604f6a6',
    messagingSenderId: '1014523318355',
    projectId: 'automated-attendence-6fc07',
    storageBucket: 'automated-attendence-6fc07.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

}
